-- V1__enums.sql — enum types (DM §2)
CREATE TYPE user_role AS ENUM
  ('CUSTOMER','SUPER_ADMIN','OPERATIONS','SALES','FINANCE','AUDITOR');
CREATE TYPE user_status AS ENUM ('ACTIVE','BLOCKED');
CREATE TYPE seller_type AS ENUM ('OWN_COMPANY','THIRD_PARTY');       -- THIRD_PARTY = Phase 3
CREATE TYPE project_status AS ENUM ('DRAFT','PUBLISHED','PAUSED','ARCHIVED');
CREATE TYPE plot_status AS ENUM ('AVAILABLE','BLOCKED','BOOKED','SOLD','WITHDRAWN');
CREATE TYPE booking_status AS ENUM
  ('BLOCKED','BOOKED','EXPIRED','CANCELLED','MANUAL_REVIEW');
CREATE TYPE payment_status AS ENUM
  ('CREATED','SUCCESS','FAILED','MANUAL_REVIEW','REFUND_INITIATED','REFUNDED');
CREATE TYPE approval_status AS ENUM ('PENDING','APPROVED','REJECTED','WITHDRAWN');
CREATE TYPE approval_action AS ENUM (
  'UPDATE_PLOT_PRICE','FORCE_PLOT_STATUS','CANCEL_BOOKING','EXTEND_HOLD',
  'RESOLVE_MANUAL_REVIEW','INITIATE_REFUND','PUBLISH_PROJECT','UPDATE_ADVANCE_CAP',
  'BULK_PRICE_UPDATE','UPDATE_GLOBAL_SETTING');
CREATE TYPE notification_channel AS ENUM ('PUSH','SMS','WHATSAPP');
