-- V1__enums.sql — enum types (DM §2)
CREATE TYPE user_role AS ENUM
  ('CUSTOMER','SUPER_ADMIN','OPERATIONS','SALES','FINANCE','AUDITOR');
CREATE TYPE user_status AS ENUM ('ACTIVE','BLOCKED');
CREATE TYPE seller_type AS ENUM ('OWN_COMPANY','THIRD_PARTY');       -- THIRD_PARTY = Phase 3
CREATE TYPE project_status AS ENUM ('DRAFT','PUBLISHED','PAUSED','ARCHIVED');
-- Gem Housing reserve flow (08 §4). BLOCKED/BOOKED are dormant — used only by the payment
-- module + its tests (PAYMENTS_ENABLED); ON_HOLD/RESERVED are the active reservation states.
CREATE TYPE plot_status AS ENUM
  ('AVAILABLE','ON_HOLD','RESERVED','SOLD','WITHDRAWN','BLOCKED','BOOKED');
CREATE TYPE booking_status AS ENUM
  ('PENDING_CONFIRMATION','PENDING_APPROVAL','RESERVED','EXPIRED','CANCELLED','REJECTED',
   'BLOCKED','BOOKED','MANUAL_REVIEW');            -- last three dormant (payments)
CREATE TYPE otp_purpose AS ENUM ('LOGIN','RESERVE');
CREATE TYPE payment_status AS ENUM
  ('CREATED','SUCCESS','FAILED','MANUAL_REVIEW','REFUND_INITIATED','REFUNDED');
CREATE TYPE approval_status AS ENUM ('PENDING','APPROVED','REJECTED','WITHDRAWN');
CREATE TYPE approval_action AS ENUM (
  'RESERVE_PLOT','UPDATE_PLOT_PRICE','FORCE_PLOT_STATUS','CANCEL_BOOKING','EXTEND_HOLD',
  'RESOLVE_MANUAL_REVIEW','INITIATE_REFUND','PUBLISH_PROJECT','UPDATE_ADVANCE_CAP',
  'BULK_PRICE_UPDATE','UPDATE_GLOBAL_SETTING');
CREATE TYPE notification_channel AS ENUM ('PUSH','SMS','WHATSAPP');
