// All user-facing copy (§11). English only in Phase 1; a future Tamil pass edits this object.

export const S = {
  brand: {
    name: 'Gem Plots',
    by: 'by Gem Housing',
  },
  nav: {
    home: 'Home',
    myPlots: 'My Plots',
    login: 'Log in',
    logout: 'Log out',
  },
  dev: {
    ribbon: 'DEV MODE — demo build. OTP codes are shown on screen.',
    otpFor: (email: string) => `DEV MODE — OTP for ${email}`,
    tapToFill: 'tap to fill',
  },
  common: {
    retry: 'Retry',
    loading: 'Loading…',
    somethingWrong: 'Something went wrong.',
    back: 'Back',
    cancel: 'Cancel',
    loadMore: 'Load more',
    save: 'Save',
  },
  home: {
    title: 'Projects',
    empty: 'New projects coming soon',
    error: 'Could not load projects.',
    reraBadge: (n: string | null) => (n ? `RERA ${n}` : 'RERA registered'),
    availability: (a: number, t: number) => `${a}/${t} plots available`,
  },
  login: {
    title: 'Log in',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    sendCode: 'Send code',
    codeSentTo: (email: string) => `We emailed a 6-digit code to ${email}`,
    verify: 'Verify',
    resend: 'Resend code',
    resendIn: (s: number) => `Resend in ${s}s`,
    editEmail: 'Use a different email',
    otpInvalid: 'Wrong code, try again',
    otpExpired: 'That code expired — request a new one',
    rateLimited: (s: number) => `Too many attempts. Try again in ${s}s`,
  },
  project: {
    mapTab: 'Map',
    listTab: 'List',
    more: 'more',
    less: 'less',
    legend: {
      available: 'Available',
      onhold: 'On hold',
      reserved: 'Reserved',
      sold: 'Sold',
    },
    mapMissing: 'Site map coming soon — plots will appear here',
    error: 'Could not load this project.',
    noPlots: 'No plots to show yet',
  },
  plot: {
    area: 'Area',
    dimensions: 'Dimensions',
    facing: 'Facing',
    price: 'Price',
    reserve: 'Reserve this plot',
    onHold: 'On hold',
    reserved: 'Reserved',
    sold: 'Sold',
    withdrawn: 'Unavailable',
    onHoldUntil: (when: string) => `On hold until ${when}`,
    beatenToIt: 'Someone just beat you to it — pick another plot',
    holdLimit: (limit: number) => `You can hold up to ${limit} plots at once`,
    duplicateHold: 'You already have an active hold on this plot',
  },
  reserve: {
    steps: ['Requested', 'Verify email', 'Gem Housing review', 'Reserved'],
    verifyTitle: 'Verify your email',
    verifyBody: 'We emailed a 6-digit code to your registered email. Enter it to continue.',
    verifyWithin: 'Verify within',
    confirm: 'Confirm',
    resend: 'Resend code',
    resendToStart: 'Send a new code to continue',
    reviewTitle: 'Awaiting approval',
    reviewBody:
      "Our team is reviewing your request. You'll get an email — most requests are decided within 48 hours.",
    decisionWithin: 'Decision expected within',
    reservedTitle: 'Reserved in your name',
    reservedBody:
      'Gem Housing will contact you at your registered email to complete the paperwork.',
    expiredTitle: 'Reservation expired',
    expiredBody: 'This hold timed out before it was confirmed.',
    rejectedTitle: 'Not approved',
    rejectedBody: 'Gem Housing was unable to approve this reservation.',
    cancelledTitle: 'Cancelled',
    cancelledBody: 'This reservation was cancelled.',
    backTo: (project: string) => `Back to ${project}`,
    notFound: 'Reservation not found',
  },
  me: {
    title: 'My Plots',
    profilePrompt: 'Complete your profile',
    profileBody: 'So our team can reach you about your reservation',
    fullName: 'Full name',
    phone: 'Phone number',
    saveProfile: 'Save',
    profileSaved: 'Profile updated',
    reservations: 'Your reservations',
    empty: 'No reservations yet — find your plot',
    findPlot: 'Browse projects',
    error: 'Could not load your reservations.',
  },
  status: {
    PENDING_CONFIRMATION: 'Verify email',
    PENDING_APPROVAL: 'Awaiting approval',
    RESERVED: 'Reserved',
    EXPIRED: 'Expired',
    REJECTED: 'Not approved',
    CANCELLED: 'Cancelled',
    AVAILABLE: 'Available',
    ON_HOLD: 'On hold',
    SOLD: 'Sold',
    WITHDRAWN: 'Withdrawn',
  } as Record<string, string>,
  admin: {
    loginTitle: 'Gem Plots Admin',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    invalidCreds: 'Invalid email or password',
    nav: {
      home: 'Home',
      inbox: 'Inbox',
      projects: 'Projects',
      notifications: 'Notifications',
      emails: 'Emails',
      audit: 'Audit',
    },
    home: {
      title: 'Dashboard',
      pendingApprovals: 'Pending approvals',
      activeHolds: 'Active holds',
      inventory: 'Inventory',
      recentActivity: 'Recent activity',
      viewAll: 'View all',
      noHolds: 'No active holds',
      noActivity: 'No recent activity',
    },
    inbox: {
      title: 'Approvals inbox',
      empty: 'Inbox zero — no pending approvals',
      age: 'Age',
      action: 'Action',
      entity: 'Entity',
      requestedBy: 'Requested by',
      reason: 'Reason',
      statusFilter: 'Status',
      actionFilter: 'Action',
      reservePlot: 'Plot reservation',
    },
    review: {
      customer: 'Customer',
      emailVerified: 'Email verified',
      plot: 'Plot',
      price: 'Price',
      decisionWithin: 'Decision window',
      guardrails: 'Guardrails',
      approve: 'Approve',
      reject: 'Reject',
      note: 'Note',
      noteOptional: 'Note (optional)',
      noteRequired: 'Reason for rejection (required)',
      approveConfirm: 'Approve this reservation?',
      rejectConfirm: 'Reject this reservation?',
      approved: 'Approved',
      rejected: 'Rejected',
      selfApproval: 'You cannot approve your own request',
      guardrailFailed: 'A guardrail failed — cannot approve',
      notPending: 'This approval is no longer pending',
      blockedByGuardrail: 'Resolve failing guardrails before approving',
    },
    projects: {
      title: 'Projects',
      managedNote: 'Projects are managed via the API in this build.',
      name: 'Name',
      status: 'Status',
      district: 'District',
      plots: 'Plots',
    },
    notifications: {
      title: 'Notifications',
      markAllRead: 'Mark all read',
      empty: 'No notifications',
    },
    emails: {
      title: 'Emails (outbox)',
      subtitle:
        'Demo mode logs every email instead of sending it. This is the mail the flow generated.',
      to: 'To',
      template: 'Template',
      subject: 'Subject',
      status: 'Status',
      time: 'Time',
      empty: 'No emails yet',
    },
    audit: {
      title: 'Audit log',
      time: 'Time (IST)',
      actor: 'Actor',
      action: 'Action',
      entity: 'Entity',
      requestId: 'Request ID',
      empty: 'No audit entries',
    },
    bell: {
      title: 'Notifications',
      viewAll: 'View all',
      empty: 'You are all caught up',
    },
  },
};
