// All user-facing copy (§11). English only in Phase 1; a future Tamil pass edits this object.

export const S = {
  brand: {
    name: 'Gem Plots',
    by: 'by Gem Housing',
  },
  nav: {
    home: 'Home',
    myPlots: 'My Plots',
    login: 'Log in',
    logout: 'Log out',
  },
  dev: {
    ribbon: 'DEV MODE — demo build. OTP codes are shown on screen.',
    otpFor: (email: string) => `DEV MODE — OTP for ${email}`,
    tapToFill: 'tap to fill',
  },
  common: {
    retry: 'Retry',
    loading: 'Loading…',
    somethingWrong: 'Something went wrong.',
    back: 'Back',
    cancel: 'Cancel',
    loadMore: 'Load more',
    save: 'Save',
  },
  home: {
    title: 'Projects',
    empty: 'New projects coming soon',
    error: 'Could not load projects.',
    reraBadge: (n: string | null) => (n ? `RERA ${n}` : 'RERA registered'),
    availability: (a: number, t: number) => `${a}/${t} plots available`,
  },
  login: {
    title: 'Log in',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    sendCode: 'Send code',
    codeSentTo: (email: string) => `We emailed a 6-digit code to ${email}`,
    verify: 'Verify',
    resend: 'Resend code',
    resendIn: (s: number) => `Resend in ${s}s`,
    editEmail: 'Use a different email',
    otpInvalid: 'Wrong code, try again',
    otpExpired: 'That code expired — request a new one',
    rateLimited: (s: number) => `Too many attempts. Try again in ${s}s`,
  },
  project: {
    mapTab: 'Map',
    listTab: 'List',
    more: 'more',
    less: 'less',
    legend: {
      available: 'Available',
      onhold: 'On hold',
      reserved: 'Reserved',
      sold: 'Sold',
    },
    mapMissing: 'Site map coming soon — plots will appear here',
    error: 'Could not load this project.',
    noPlots: 'No plots to show yet',
  },
  plot: {
    area: 'Area',
    dimensions: 'Dimensions',
    facing: 'Facing',
    price: 'Price',
    reserve: 'Reserve this plot',
    onHold: 'On hold',
    reserved: 'Reserved',
    sold: 'Sold',
    withdrawn: 'Unavailable',
    onHoldUntil: (when: string) => `On hold until ${when}`,
    beatenToIt: 'Someone just beat you to it — pick another plot',
    holdLimit: (limit: number) => `You can hold up to ${limit} plots at once`,
    duplicateHold: 'You already have an active hold on this plot',
  },
  reserve: {
    steps: ['Requested', 'Verify email', 'Gem Housing review', 'Reserved'],
    verifyTitle: 'Verify your email',
    verifyBody: 'We emailed a 6-digit code to your registered email. Enter it to continue.',
    verifyWithin: 'Verify within',
    confirm: 'Confirm',
    resend: 'Resend code',
    resendToStart: 'Send a new code to continue',
    reviewTitle: 'Awaiting approval',
    reviewBody:
      "Our team is reviewing your request. You'll get an email — most requests are decided within 48 hours.",
    decisionWithin: 'Decision expected within',
    reservedTitle: 'Reserved in your name',
    reservedBody:
      'Gem Housing will contact you at your registered email to complete the paperwork.',
    expiredTitle: 'Reservation expired',
    expiredBody: 'This hold timed out before it was confirmed.',
    rejectedTitle: 'Not approved',
    rejectedBody: 'Gem Housing was unable to approve this reservation.',
    cancelledTitle: 'Cancelled',
    cancelledBody: 'This reservation was cancelled.',
    backTo: (project: string) => `Back to ${project}`,
    notFound: 'Reservation not found',
  },
  me: {
    title: 'My Plots',
    profilePrompt: 'Complete your profile',
    profileBody: 'So our team can reach you about your reservation',
    fullName: 'Full name',
    phone: 'Phone number',
    saveProfile: 'Save',
    profileSaved: 'Profile updated',
    reservations: 'Your reservations',
    empty: 'No reservations yet — find your plot',
    findPlot: 'Browse projects',
    error: 'Could not load your reservations.',
  },
  status: {
    PENDING_CONFIRMATION: 'Verify email',
    PENDING_APPROVAL: 'Awaiting approval',
    RESERVED: 'Reserved',
    EXPIRED: 'Expired',
    REJECTED: 'Not approved',
    CANCELLED: 'Cancelled',
    AVAILABLE: 'Available',
    ON_HOLD: 'On hold',
    SOLD: 'Sold',
    WITHDRAWN: 'Withdrawn',
  } as Record<string, string>,
  admin: {
    loginTitle: 'Gem Plots Admin',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    invalidCreds: 'Invalid email or password',
    nav: {
      home: 'Home',
      inbox: 'Inbox',
      projects: 'Projects',
      notifications: 'Notifications',
      emails: 'Emails',
      audit: 'Audit',
      settings: 'Settings',
    },
    home: {
      title: 'Dashboard',
      pendingApprovals: 'Pending approvals',
      activeHolds: 'Active holds',
      inventory: 'Inventory',
      recentActivity: 'Recent activity',
      viewAll: 'View all',
      noHolds: 'No active holds',
      noActivity: 'No recent activity',
    },
    inbox: {
      title: 'Approvals inbox',
      empty: 'Inbox zero — no pending approvals',
      age: 'Age',
      action: 'Action',
      entity: 'Entity',
      requestedBy: 'Requested by',
      reason: 'Reason',
      statusFilter: 'Status',
      actionFilter: 'Action',
      reservePlot: 'Plot reservation',
      updatePlotPrice: 'Plot price change',
      forcePlotStatus: 'Plot status override',
      cancelBooking: 'Booking cancellation',
      extendHold: 'Hold extension',
      publishProject: 'Project status change',
      updateAdvanceCap: 'Advance cap change',
      bulkPriceUpdate: 'Bulk price update',
      updateGlobalSetting: 'Setting change',
    },
    review: {
      customer: 'Customer',
      emailVerified: 'Email verified',
      plot: 'Plot',
      price: 'Price',
      decisionWithin: 'Decision window',
      guardrails: 'Guardrails',
      approve: 'Approve',
      reject: 'Reject',
      note: 'Note',
      noteOptional: 'Note (optional)',
      noteRequired: 'Reason for rejection (required)',
      approveConfirm: 'Approve this reservation?',
      rejectConfirm: 'Reject this reservation?',
      approved: 'Approved',
      rejected: 'Rejected',
      selfApproval: 'You cannot approve your own request',
      guardrailFailed: 'A guardrail failed — cannot approve',
      notPending: 'This approval is no longer pending',
      blockedByGuardrail: 'Resolve failing guardrails before approving',
      changes: 'Proposed change',
      field: 'Field',
      current: 'Current',
      proposed: 'Proposed',
      driftWarning: 'Changed since request',
    },
    projects: {
      title: 'Projects',
      name: 'Name',
      status: 'Status',
      district: 'District',
      plots: 'Plots',
      rera: 'RERA',
      reraYes: 'Registered',
      newProject: 'New project',
      empty: 'No projects yet — create your first',
      error: 'Could not load projects.',
      // Create form
      createTitle: 'New project',
      fieldName: 'Project name',
      fieldDescription: 'Description',
      fieldAddress: 'Address line',
      fieldDistrict: 'District',
      fieldState: 'State',
      fieldPincode: 'Pincode',
      fieldLat: 'Latitude',
      fieldLng: 'Longitude',
      fieldAmenities: 'Amenities (comma-separated)',
      fieldReraRegistered: 'RERA registered',
      fieldReraNumber: 'RERA number',
      fieldAdvancePct: 'Max advance %',
      fieldHoldOverride: 'Hold minutes override',
      create: 'Create project',
      nameRequired: 'Project name is required',
      reraNumberRequired: 'RERA number is required when RERA registered',
      created: 'Project created',
      createError: 'Could not create project.',
    },
    projectDetail: {
      notFound: 'Project not found',
      publishNote: 'Status changes go through a maker-checker approval.',
      publish: 'Request publish',
      publishRequested: 'Publish request sent for approval',
      publishError: 'Could not request publish.',
      publishPending: 'A publish request is already pending approval.',
      currentStatus: 'Current status',
      tabs: { details: 'Details', plots: 'Plots', map: 'Site map' },
      // Details tab
      controlledNote: 'changes require a maker-checker approval',
      saveDetails: 'Save changes',
      detailsSaved: 'Project updated',
      detailsError: 'Could not save changes.',
      nothingToSave: 'No changes to save',
      // Plots tab
      plotNumber: 'Plot',
      facing: 'Facing',
      area: 'Area',
      price: 'Price',
      plotStatus: 'Status',
      noPlots: 'No plots yet — import some below',
      csvTitle: 'Import plots from CSV',
      csvHelper: 'Columns: plot_number,facing,dimensions_text,area_sqft,price_inr',
      csvPickFile: 'Choose CSV file',
      csvPaste: 'or paste CSV here',
      csvPreview: 'Preview',
      csvValidate: 'Validate',
      csvImport: 'Import',
      csvRow: 'Row',
      csvNoRows: 'No rows parsed yet',
      csvImported: (n: number) => `${n} plot${n === 1 ? '' : 's'} imported`,
      csvHasErrors: 'Fix the errors before importing',
      csvError: 'Could not process the CSV.',
      // Site map tab
      mapVersion: 'Version',
      mapActive: 'Active',
      mapDimensions: 'Dimensions',
      mapCreated: 'Created',
      mapOpenEditor: 'Open editor',
      mapUploadNew: 'Upload new version',
      mapUploading: 'Uploading…',
      noMaps: 'No site maps yet — upload one to place plots',
      mapUploaded: 'Site map uploaded',
      mapUploadError: 'Could not upload the site map.',
      mapBadImage: 'Could not read that image.',
    },
    editor: {
      back: 'Back to project',
      title: (v: number) => `Site map editor — v${v}`,
      tools: 'Tools',
      draw: 'Draw',
      edit: 'Edit',
      done: 'Done',
      undo: 'Undo',
      save: 'Save',
      activate: 'Activate',
      deleteSelected: 'Delete selected',
      plots: 'Plots',
      assigned: 'assigned',
      unassigned: 'unassigned',
      assignPrompt: 'Assign this shape to a plot',
      cancel: 'Cancel',
      hintDraw: 'Click to add points; click the first point or press Enter to close (min 3).',
      hintEdit: 'Click a shape to select, then drag its points. Delete removes it.',
      saved: 'Geometries saved',
      saveError: 'Could not save geometries.',
      activateConfirm: (v: number) => `Activate site map v${v}?`,
      activateBody: 'This becomes the live map customers see. Every plot must be assigned.',
      activated: (v: number) => `Map v${v} is now live`,
      incomplete: 'Assign all plots first',
      needClose: 'Add at least 3 points to close the shape.',
    },
    notifications: {
      title: 'Notifications',
      markAllRead: 'Mark all read',
      empty: 'No notifications',
    },
    emails: {
      title: 'Emails (outbox)',
      subtitle:
        'Demo mode logs every email instead of sending it. This is the mail the flow generated.',
      to: 'To',
      template: 'Template',
      subject: 'Subject',
      status: 'Status',
      time: 'Time',
      empty: 'No emails yet',
    },
    audit: {
      title: 'Audit log',
      time: 'Time (IST)',
      actor: 'Actor',
      action: 'Action',
      entity: 'Entity',
      requestId: 'Request ID',
      empty: 'No audit entries',
    },
    settings: {
      title: 'Global settings',
      subtitle:
        'Operational config. Changes are maker-checker: a SUPER_ADMIN requests, a different SUPER_ADMIN approves. Live holds are never affected.',
      key: 'Setting',
      value: 'Value',
      updated: 'Updated',
      edit: 'Edit',
      save: 'Request change',
      cancel: 'Cancel',
      requested: 'Change requested for approval',
      error: 'Could not request the change.',
      pending: 'A change for this setting is already pending approval.',
      noAccess: 'You do not have access to settings.',
      empty: 'No settings',
    },
    bell: {
      title: 'Notifications',
      viewAll: 'View all',
      empty: 'You are all caught up',
    },
  },
};
